images:
  repository: ghcr.io/PhuThuan323   # Thay bằng GitHub org của team
  tag: latest                       # ArgoCD sẽ override cái này

frontend:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/frontendservice
    tag: latest

cartservice:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/cartservice
    tag: latest

checkoutservice:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/checkoutservice
    tag: latest

currencyservice:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/currencyservice
    tag: latest

emailservice:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/emailservice
    tag: latest

loadgeneratorservice:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/loadgeneratorservice
    tag: latest

paymentservice:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/paymentservice
    tag: latest

productcatalogservice:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/productcatalogservice
    tag: latest

recommendationservice:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/recommendationservice
    tag: latest

shippingservice:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/shippingservice
    tag: latest

shoppingassistantservice:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  image:
    repository: ghcr.io/PhuThuan323/shoppingassistantservice
    tag: latest