name: CI - shoppingassistantservice

on:
  push:
    branches: [main]
    paths:
      - 'src/shoppingassistantservice/**'
      - 'apps/values.yml'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/ci-service.yml
    with:
      service_name: shoppingassistantservice
      service_path: ./src/shoppingassistantservice